onlineshop/urls.py
from django.urls import path
from . import views
from django.urls import re_path

from .views import AllClientsForEmployeeView, LogoutView

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('products/', views.ProductListView.as_view(), name='products'),
#
#
#     path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
# ]

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^products/$', views.ProductListView.as_view(), name='products'),
    re_path(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturers'),
    re_path(r'^manufacturers/(?P<pk>\d+)$', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
]
urlpatterns += [
    re_path(r'^myproducts/$', views.OrderedProductsByUserListView.as_view(), name='my-ordered'),
]
urlpatterns += [
    re_path(r'^all-orders/$', views.AllOrdersForEmployeeView.as_view(), name='all-orders'),
]
urlpatterns += [
    re_path(r'^order/(?P<pk>[-\w]+)/change-status/$', views.change_status_employee, name='change-status-employee'),

]
urlpatterns += [
    re_path(r'^orders/$', views.OrdersByUserListView.as_view(), name='my-orders'),
]
urlpatterns += [
    re_path(r'^orders/(?P<order_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', views.OrderedProductsByUserListView.as_view(), name='order-detail'),
]
urlpatterns += [
    # ... your other url patterns here ...

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]
urlpatterns += [
    re_path(r'^cart/$', views.CartView.as_view(), name='cart'),
]
urlpatterns += [
    path('create-order/', views.create_order, name='create-order'),
]

urlpatterns += [
    re_path(r'^increase-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.increase_quantity,
            name='increase-quantity'),
    re_path(r'^decrease-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.decrease_quantity,
            name='decrease-quantity'),
    re_path(r'^remove-from-cart/(?P<product_instance_id>[0-9a-f-]+)/$', views.remove_from_cart,
            name='remove-from-cart'),
]

urlpatterns += [
    path('onlineshop/cart/apply-promo-code/', views.apply_promo_code, name='apply-promo-code'),
]
urlpatterns += [
    path('promo-codes/', views.PromoCodeListView.as_view(), name='promo-codes'),
]
urlpatterns += [
    path('pickup-locations/', views.PickupLocationListView.as_view(), name='pickup-locations'),
]
urlpatterns += [
    path('clients/', views.client_list, name='clients'),
]

urlpatterns += [
    path('clients/all/', views.AllClientsForEmployeeView.as_view(), name='all-clients'),
]
from .views import EmployeeListView

urlpatterns += [
    path('contacts/', EmployeeListView.as_view(), name='contacts'),
]
from .views import ReviewListView, ReviewCreateView

urlpatterns += [
    path('reviews/', ReviewListView.as_view(), name='reviews'),
    path('reviews/add/', ReviewCreateView.as_view(), name='add-review'),
]
from .views import employee_stats

urlpatterns += [
    path('employee-stats/', employee_stats, name='employee-stats'),
]
urlpatterns += [
    path('logout/', LogoutView.as_view(), name='logout'),
]
urlpatterns += [
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
]
urlpatterns += [
    path('news/', views.news, name='news'),
    path('news/<int:article_id>/', views.article_detail, name='article_detail'),
]
urlpatterns += [
    path('about/', views.about, name='about'),
]
urlpatterns += [
    path('faq/', views.faq, name='faq'),
]
urlpatterns += [
    path('jobs/', views.jobs, name='jobs'),
]

onlineshop/models.py
import uuid

from django.db import models
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.urls import reverse

import sys
from django.contrib.auth.models import User, Group

sys.path.append('D:\\3 SEM\\253503_TIMOSHEVICH_25\\IGI\\LR5\\LabRab5_IGI\\.venv\\Lib\\site-packages')

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=3)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='', null=True, blank=True)
    job_description = models.TextField(default='')  # new field
    phone = models.CharField(max_length=20, default='')  # new field
    email = models.EmailField(default='default@email.com')  # new field

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Employees')
        self.user.groups.add(group)


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=2)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)  # new field
    phone_number = models.CharField(max_length=20, default='', blank=True)  #

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        ordering = ["last_name", "first_name"]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Shop Members')
        self.user.groups.add(group)


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer-detail', args=[str(self.id)])


class UnitOfMeasure(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey("Manufacturer", on_delete=models.CASCADE, null=True)
    unit_of_measure = models.ForeignKey(UnitOfMeasure, on_delete=models.SET_NULL, null=True)

    # image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    customer = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def total_price(self):
        return self.product.price * self.quantity

    class Meta:
        permissions = (("can_mark_issued", "Set product as issued"),)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.product.name)


class PickupLocation(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class PromoCode(models.Model):
    code = models.CharField(max_length=10)
    discount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.code


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field
    pickup_location = models.ForeignKey(PickupLocation, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Processing'),
        ('s', 'Shipped'),
        ('d', 'Delivered'),
        ('i', 'Issued'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='p',
                              help_text='Status of the order')

    def save(self, *args, **kwargs):
        self.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            self.total_price *= (1 - self.promo_code.discount / 100)
        super().save(*args, **kwargs)

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()

    def __str__(self):
        return f"Order {self.id} by {self.client}"


@receiver(m2m_changed, sender=Order.products.through)
def update_total_price(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove":
        instance.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in instance.products.all())
        instance.save()


class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)  # new field

    def __str__(self):
        return f"Cart for {self.client}"

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    content = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class CompanyInfo(models.Model):
    text = models.TextField()
    video = models.FileField(upload_to='company_info/')
    logo = models.ImageField(upload_to='company_info/')
    history = models.TextField()
    details = models.TextField()

    def __str__(self):
        return "Company Information"


class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question


class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

onlineshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.

from .models import Order, PickupLocation


class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date, timedelta
from django.core.validators import RegexValidator


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    date_of_birth = forms.DateField(
        help_text="Required. Format: DD.MM.YYYY",
        input_formats=['%d.%m.%Y']
    )
    phone_number = forms.CharField(
        validators=[
            RegexValidator(
                regex=r'^\+375 \((29|33|44|25)\) \d{3}-\d{2}-\d{2}$',
                message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'. Up to 15 digits allowed."
            )
        ]
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "email", "password1", "password2", "date_of_birth", "phone_number"]

    def clean_date_of_birth(self):
        dob = self.cleaned_data.get('date_of_birth')
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('You must be at least 18 years old to register.')
        return dob

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['pickup_location']
        widgets = {
            'pickup_location': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['pickup_location'].empty_label = None

from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]  # Choices from 1 to 5

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.Select(), required=True)

    class Meta:
        model = Review
        fields = ['rating', 'text']

onlineshop/templates/onlineshop/article_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width:300px; max-height:300px;">
    <p>{{ article.content }}</p>
{% endblock %}

onlineshop/templates/onlineshop/change_status_employee.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Change Order Status</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change Status</button>
    </form>

    <h2>Order Details</h2>
    <ul>
    {% for product in order.products.all %}
        <li>{{ product.product.name }} (Quantity: {{ product.quantity }})</li>
    {% endfor %}
    </ul>

    <a href="{% url 'all-orders' %}">Back to All Orders</a>

{% endblock %}

onlineshop/templates/onlineshop/client_list_for_employee.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Client List</h1>

  <form method="GET" action="{% url 'clients' %}">
    <input type="text" name="search" placeholder="Search clients" value="{{ request.GET.search }}">
    <input type="submit" value="Search">
  </form>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Date Joined</th>
      </tr>
    </thead>
    <tbody>
    {% for client in object_list %}
      <tr>
        <td>{{ client.user.username }}</td>
        <td>{{ client.user.email }}</td>
        <td>{{ client.user.date_joined }}</td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="3">No clients found.</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

onlineshop/templates/onlineshop/employee_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Contacts</h1>

  {% for employee in object_list %}
    <div>
      {% if employee.photo %}
        <img src="{{ employee.photo.url }}" alt="{{ employee.first_name }} {{ employee.last_name }}" width="200">
      {% endif %}
      <h2>{{ employee.first_name }} {{ employee.last_name }}</h2>
      <p>{{ employee.position }}</p>
      {% if employee.job_description %}
        <p>{{ employee.job_description }}</p>
      {% endif %}
      {% if employee.phone %}
        <p>Phone: {{ employee.phone }}</p>
      {% endif %}
      {% if employee.email %}
        <p>Email: <a href="mailto:{{ employee.email }}">{{ employee.email }}</a></p>
      {% endif %}
    </div>
  {% empty %}
    <p>No employees found.</p>
  {% endfor %}
{% endblock %}

onlineshop/templates/onlineshop/faq.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>FAQ</h1>
    {% for faq in faqs %}
        <div>
            <h2>{{ faq.question }}</h2>
            <p>{{ faq.answer }}</p>
            <p>Date added: {{ faq.date_added }}</p>
        </div>
    {% endfor %}
{% endblock %}

onlineshop/templates/onlineshop/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ manufacturer.name }}</h1>

  <p><strong>Description:</strong> {{ manufacturer.description }}</p>
  <p><strong>Location:</strong> {{ manufacturer.location }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Products</h4>

    {% for product in manufacturer.product_set.all %}
    <hr>
    <p><strong>Name:</strong> <a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
    <p><strong>Price:</strong> {{ product.price }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ product.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

onlineshop/templates/onlineshop/news.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>News</h1>
    {% for article in articles %}
        <div>
            <h2>{{ article.title }}</h2>
            <p>{{ article.summary }}</p>
            <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width:300px; max-height:300px;">
            <a href="{% url 'article_detail' article.id %}">Read more</a>
        </div>
    {% endfor %}
{% endblock %}

onlineshop/templates/onlineshop/orders_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Order List</h1>

    {% if order_list %}
    <ul>
      {% for order in order_list %}
      <li>
       <a href="{% url 'order-detail' order.id %}">Order {{ order.order_date|date:"d.m.Y" }} - {{ order.get_status_display }}</a> (Total price: {{ order.total_price }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>You have no orders.</p>
    {% endif %}
{% endblock %}

onlineshop/templates/onlineshop/pickup_location_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Pickup Locations</h1>
  <ul>
    {% for location in object_list %}
      <li>
        <h2>{{ location.name }}</h2>
        <p>Address: {{ location.address }}</p>
      </li>
    {% empty %}
      <li>No pickup locations available.</li>
    {% endfor %}
  </ul>
{% endblock %}

onlineshop/templates/onlineshop/privacy_policy.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Privacy policy</h1>
    Здесь будет политика конфиденциальности... скоро
{% endblock %}

onlineshop/templates/onlineshop/product_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ product.name }}</h1>

  <p><strong>Description:</strong> {{ product.description }}</p>
  <p><strong>Price:</strong> {{ product.price }}</p>
  <p><strong>Product type:</strong> {{ product.product_type }}</p>
  <p><strong>Unit of measure:</strong> {{ product.unit_of_measure }}</p>
  <p><strong>Manufacturer:</strong> <a href="{% url 'manufacturer-detail' product.manufacturer.id %}">{{ product.manufacturer }}</a></p>
  {% if user.is_authenticated and user.client %}
  <form method="POST" action="{% url 'add_to_cart' product.id %}">
    {% csrf_token %}
    <input type="submit" value="Add to cart">
  </form>
  {% endif %}
{% endblock %}

onlineshop/templates/onlineshop/productinstance_list_all_orders.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Orders</h1>

    {% if order_list %}
    <ul>
      {% for order in order_list %}
      <li>
         <a href="{% url 'change-status-employee' order.id %}">Order {{ order.order_date|date:"d.m.Y" }} - {{ order.get_status_display }}</a> (Total price: {{ order.total_price }}, Ordered by: {{ order.client.user.username }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
        <p>There are no orders.</p>
    {% endif %}
{% endblock %}

onlineshop/templates/onlineshop/promo_code_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Promo Codes</h1>
  <ul>
    {% for promo_code in object_list %}
      <li>
        <h2>{{ promo_code.code }}</h2>
        <p>Discount: {{ promo_code.discount }}%</p>
      </li>
    {% empty %}
      <li>No promo codes available.</li>
    {% endfor %}
  </ul>
{% endblock %}

onlineshop/templates/onlineshop/user_cart.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Cart</h1>

    {% if cart.products.all %}
    <ul>
      {% for product_instance in cart.products.all %}
      <li>
            <a href="{% url 'product-detail' product_instance.product.id %}">{{ product_instance.product.name }}</a> (Quantity: {{ product_instance.quantity }}, Price: {{ product_instance.product.price }}, Total: <span id="total-price-{{ product_instance.id }}">{{ product_instance.total_price }}</span>)
            <div style="display: flex;">
                <form action="{% url 'increase-quantity' product_instance.id %}" method="post" class="quantity-form" data-product-instance-id="{{ product_instance.id }}">
                    {% csrf_token %}
                    <input type="submit" value="+">
                </form>
                <form action="{% url 'decrease-quantity' product_instance.id %}" method="post" class="quantity-form" data-product-instance-id="{{ product_instance.id }}">
                    {% csrf_token %}
                    <input type="submit" value="-">
                </form>
                <form action="{% url 'remove-from-cart' product_instance.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить из корзины">
                </form>
            </div>
      </li>
      {% endfor %}
    </ul>
         <!-- Promo code form -->
    <form action="{% url 'apply-promo-code' %}" method="post">
        {% csrf_token %}
        <input type="text" name="promo_code" placeholder="Enter promo code">
        <input type="submit" value="Apply Promo Code">
    </form>

    <p>Total price: {{ cart.total_price }}</p>
      <form method="post" action="{% url 'create-order' %}">
        {% csrf_token %}
        <h2>Select a pickup location:</h2>
        {{ form.as_p }}
        <button type="submit">Place order</button>
      </form>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}
{% endblock %}